/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{html,ts}'],
  darkMode: ['selector', '[data-theme="dark"]'],
  theme: {
    extend: {},
  },
  plugins: [require('daisyui')],
  daisyui: {
    themes: [
      'dark',
      'synthwave',
      'halloween',
      'forest',
      'black',
      'luxury',
      'dracula',
      'business',
      'night',
      'coffee',
      'sunset',
      'dim',
      'light',
      'cupcake',
      'bumblebee',
      'emerald',
      'corporate',
      'retro',
      'cyberpunk',
      'valentine',
      'garden',
      'lofi',
      'pastel',
      'fantasy',
      'wireframe',
      'cmyk',
      'autumn',
      'acid',
      'lemonade',
      'winter',
      'nord',
    ],
    styled: true,
    themes: true,
    base: true,
    utils: true,
    logs: true,
    rtl: false,
  },
};
