import {
  gameAges,
  gameClockwork,
  gameExitDoor,
  gameGlassHeart,
  gameGooeyImpact,
  gameHumanTarget,
  gameIceCube,
  gamePauseButton,
  gamePlainCircle,
  gamePlayButton,
  gameSmallFire,
  gameStonePile,
  gameSwanBreeze,
  gameVibratingShield,
} from '@ng-icons/game-icons';
import {
  tablerCheck,
  tablerPlus,
  tablerSettings,
  tablerX,
} from '@ng-icons/tabler-icons';

export const ALL_ICONS = {
  gameExitDoor,
  gameHumanTarget,
  gameAges,
  gameGooeyImpact,
  gameGlassHeart,
  gameClockwork,
  gameVibratingShield,
  gamePauseButton,
  gamePlayButton,
  gameSmallFire,
  gameIceCube,
  gameSwanBreeze,
  gameStonePile,
  gamePlainCircle,
  tablerPlus,
  tablerSettings,
  tablerX,
  tablerCheck,
};
